const songsConstants = {
  SET_ALL_SONGS: "SET_ALL_SONGS",
  TOOGLE_IS_SHOW_SIDEBAR: "TOOGLE_IS_SHOW_SIDEBAR",
  SET_ALL_COVERS: "SET_ALL_COVERS",
  SET_SONG_LIST_TYPE: "SET_SONG_LIST_TYPE",
  SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
  SET_CURRENT_TRACK: "SET_CURRENT_TRACK",
  SET_IS_PLAYING: "SET_IS_PLAYING",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_TRACK_INDEX: "SET_TRACK_INDEX",
};

export { songsConstants };
